"""Add hashed token fields

Revision ID: 02196377ba5c
Revises: 876717fd4d64
Create Date: 2025-10-30 16:24:54.569296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02196377ba5c'
down_revision = '876717fd4d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.String(length=255), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_token_prefix'), ['token_prefix'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_token_prefix'))

    op.drop_table('token')
    # ### end Alembic commands ###
